/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package groupproject;

import javax.swing.JOptionPane;
/**
 *
 * @author mikey
 */
public class MentalWellBeingGUI extends javax.swing.JFrame {
    private mentalWellBeing mwb;
    private moodTracker mt;
    private stressTips st;

    /**
     * Creates new form MentalWellBeingGUI
     */
    public MentalWellBeingGUI() {
        initComponents();
        mwb = new mentalWellBeing();  
        mt = new moodTracker();      
        st = new stressTips();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogMoodTF = new javax.swing.JTextField();
        LogMoodBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        StressTipsBTN = new javax.swing.JButton();
        WeeklySummaryBTN = new javax.swing.JButton();
        MentalWellBeingLBL = new javax.swing.JLabel();
        ExitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogMoodTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogMoodTFActionPerformed(evt);
            }
        });

        LogMoodBTN.setText("Log Mood");
        LogMoodBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogMoodBTNActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        StressTipsBTN.setText("Stress Tips");
        StressTipsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StressTipsBTNActionPerformed(evt);
            }
        });

        WeeklySummaryBTN.setText("Weekly Summary");
        WeeklySummaryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeeklySummaryBTNActionPerformed(evt);
            }
        });

        MentalWellBeingLBL.setText("Mental Well Being");

        ExitBTN.setText("Exit");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WeeklySummaryBTN)
                .addGap(18, 18, 18)
                .addComponent(StressTipsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(LogMoodBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogMoodTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MentalWellBeingLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitBTN)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MentalWellBeingLBL)
                .addGap(45, 45, 45)
                .addComponent(LogMoodTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WeeklySummaryBTN)
                            .addComponent(StressTipsBTN)
                            .addComponent(LogMoodBTN))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ExitBTN)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogMoodTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogMoodTFActionPerformed
      
    }//GEN-LAST:event_LogMoodTFActionPerformed

    private void WeeklySummaryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeklySummaryBTNActionPerformed
        String summary = mwb.createWeeklySummary();
        jTextArea1.setText(summary); 
    }//GEN-LAST:event_WeeklySummaryBTNActionPerformed

    private void StressTipsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StressTipsBTNActionPerformed
       String tips = "";
    for (String tip : st.fetchTips()) {  
        tips += tip + "\n";  
    }
        jTextArea1.setText(tips);
    }//GEN-LAST:event_StressTipsBTNActionPerformed

    private void LogMoodBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogMoodBTNActionPerformed
      String mood = LogMoodTF.getText().trim();  
      if(!mood.isEmpty()) {
         mwb.logMood(mood);  
         jTextArea1.setText("Mood logged: " + mood);  
         LogMoodTF.setText("");  
    } else {
        JOptionPane.showMessageDialog(this, "Please enter a mood.");  // If mood is empty
      }
    }//GEN-LAST:event_LogMoodBTNActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
     this.dispose(); 
    healthGUI goodHealthWindow = new healthGUI();
    goodHealthWindow.setVisible(true);  
    }//GEN-LAST:event_ExitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MentalWellBeingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MentalWellBeingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MentalWellBeingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MentalWellBeingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MentalWellBeingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton LogMoodBTN;
    private javax.swing.JTextField LogMoodTF;
    private javax.swing.JLabel MentalWellBeingLBL;
    private javax.swing.JButton StressTipsBTN;
    private javax.swing.JButton WeeklySummaryBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
